export const dummyResQuestion = {
  items: [
    {
      tags: ["jquery"],
      owner: {
        account_id: 60229,
        reputation: 28759,
        user_id: 179972,
        user_type: "registered",
        accept_rate: 86,
        profile_image:
          "https://www.gravatar.com/avatar/c8490a40a09ce2750351f3fa46614de1?s=256&d=identicon&r=PG",
        display_name: "John K",
        link: "https://stackoverflow.com/users/179972/john-k",
      },
      is_answered: true,
      view_count: 36118,
      accepted_answer_id: 17538213,
      answer_count: 12,
      score: 153,
      last_activity_date: 1727488629,
      creation_date: 1273764570,
      last_edit_date: 1316571098,
      question_id: 2828019,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/2828019/looking-for-jquery-find-method-that-includes-the-current-node",
      title:
        "Looking for jQuery find(..) method that  includes the current node",
    },
    {
      tags: ["javascript", "jquery", "textbox", "dropdown", "disable"],
      owner: {
        account_id: 31347815,
        reputation: 11,
        user_id: 24164513,
        user_type: "registered",
        profile_image:
          "https://www.gravatar.com/avatar/1060f9694d83734ad7546d5dc82602d7?s=256&d=identicon&r=PG&f=y&so-version=2",
        display_name: "Gary Robinson",
        link: "https://stackoverflow.com/users/24164513/gary-robinson",
      },
      is_answered: true,
      view_count: 56,
      accepted_answer_id: 79011938,
      answer_count: 1,
      score: 0,
      last_activity_date: 1727470690,
      creation_date: 1727015652,
      last_edit_date: 1727018464,
      question_id: 79011878,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/79011878/enable-disable-multiple-inputs-on-dropdown-change-selection",
      title: "Enable disable multiple inputs on dropdown change selection",
    },
    {
      tags: ["javascript", "html", "jquery"],
      owner: {
        account_id: 3855628,
        reputation: 39,
        user_id: 3194653,
        user_type: "registered",
        profile_image: "https://i.sstatic.net/BYLoW.jpg?s=256",
        display_name: "Pritesh Vikram",
        link: "https://stackoverflow.com/users/3194653/pritesh-vikram",
      },
      is_answered: true,
      view_count: 57,
      closed_date: 1727467191,
      answer_count: 2,
      score: 0,
      last_activity_date: 1727466867,
      creation_date: 1727455751,
      question_id: 79032274,
      link: "https://stackoverflow.com/questions/79032274/how-to-delete-last-character-of-text-node-from-div-element-which-has-span-as-sib",
      closed_reason: "Needs more focus",
      title:
        "How to delete last character of text node from div element which has span as sibling",
    },
    {
      tags: ["javascript", "html", "jquery"],
      owner: {
        account_id: 21510717,
        reputation: 123,
        user_id: 15853459,
        user_type: "registered",
        profile_image:
          "https://www.gravatar.com/avatar/4b26332ba940e138f219cc118b4e54f1?s=256&d=identicon&r=PG&f=y&so-version=2",
        display_name: "Rika Das",
        link: "https://stackoverflow.com/users/15853459/rika-das",
      },
      is_answered: true,
      view_count: 3778,
      answer_count: 2,
      score: 0,
      last_activity_date: 1727463570,
      creation_date: 1621844776,
      last_edit_date: 1621844939,
      question_id: 67668865,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/67668865/onclick-of-hyperlink-modal-popup-window-in-html",
      title: "Onclick of hyperlink modal popup window in html",
    },
    {
      tags: ["javascript", "jquery", "html", "image", "fancybox-2"],
      owner: {
        account_id: 4068322,
        reputation: 68,
        user_id: 3342395,
        user_type: "registered",
        profile_image:
          "https://graph.facebook.com/1281241949/picture?type=large",
        display_name: "screth",
        link: "https://stackoverflow.com/users/3342395/screth",
      },
      is_answered: true,
      view_count: 1073,
      accepted_answer_id: 22968510,
      answer_count: 1,
      score: 2,
      last_activity_date: 1727459126,
      creation_date: 1396997953,
      last_edit_date: 1727459126,
      question_id: 22949844,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/22949844/open-specific-image-in-fancybox-from-main-image-area",
      title: "Open specific image in fancybox from main image area",
    },
    {
      tags: ["javascript", "jquery", "ajax"],
      owner: {
        account_id: 27557479,
        reputation: 33,
        user_id: 21031391,
        user_type: "registered",
        profile_image:
          "https://www.gravatar.com/avatar/1218bc0943071e152d14a7468b4f0649?s=256&d=identicon&r=PG",
        display_name: "ysi_d",
        link: "https://stackoverflow.com/users/21031391/ysi-d",
      },
      is_answered: true,
      view_count: 33,
      accepted_answer_id: 79032288,
      answer_count: 1,
      score: 0,
      last_activity_date: 1727456525,
      creation_date: 1727450932,
      question_id: 79032036,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/79032036/how-do-i-use-jquery-promises-to-chain-one-ajax-call-then-a-loop-of-ajax-calls",
      title:
        "How do I use jQuery promises to chain one ajax call, then a loop of ajax calls, then make use of an accumulated result?",
    },
    {
      tags: ["javascript", "jquery"],
      owner: {
        account_id: 12321169,
        reputation: 1743,
        user_id: 8990411,
        user_type: "registered",
        profile_image:
          "https://www.gravatar.com/avatar/2af8bd6c5bef02815cd9e9ad2d5bcab0?s=256&d=identicon&r=PG&f=y&so-version=2",
        display_name: "Anatole Lucet",
        link: "https://stackoverflow.com/users/8990411/anatole-lucet",
      },
      is_answered: true,
      view_count: 12217,
      accepted_answer_id: 49432769,
      answer_count: 2,
      score: 8,
      last_activity_date: 1727455430,
      creation_date: 1521732374,
      last_edit_date: 1521732783,
      question_id: 49432520,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/49432520/argument-1-of-window-getcomputedstyle-does-not-implement-interface-element",
      title:
        "Argument 1 of Window.getComputedStyle does not implement interface Element",
    },
    {
      tags: ["javascript", "php", "jquery", "css", "datatables"],
      owner: {
        account_id: 9938079,
        reputation: 73,
        user_id: 7355708,
        user_type: "registered",
        profile_image:
          "https://www.gravatar.com/avatar/dafc3d530d519c5d7426322a74810508?s=256&d=identicon&r=PG&f=y&so-version=2",
        display_name: "Mohammed Sadakath Ali Aamiri",
        link: "https://stackoverflow.com/users/7355708/mohammed-sadakath-ali-aamiri",
      },
      is_answered: false,
      view_count: 10466,
      answer_count: 2,
      score: 3,
      last_activity_date: 1727453050,
      creation_date: 1484765774,
      last_edit_date: 1484768827,
      question_id: 41727293,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/41727293/buttons-not-showing-up-in-dombfrtip",
      title: "Buttons not showing up in Dom:&#39;Bfrtip&#39;",
    },
    {
      tags: ["jquery", "filepond"],
      owner: {
        account_id: 394295,
        reputation: 3476,
        user_id: 756659,
        user_type: "registered",
        accept_rate: 77,
        profile_image:
          "https://www.gravatar.com/avatar/7aa2bfc341345ba1e2f403830244e6d3?s=256&d=identicon&r=PG",
        display_name: "user756659",
        link: "https://stackoverflow.com/users/756659/user756659",
      },
      is_answered: false,
      view_count: 39,
      answer_count: 0,
      score: -3,
      last_activity_date: 1727449280,
      creation_date: 1727372733,
      last_edit_date: 1727449280,
      question_id: 79028572,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/79028572/filepond-confused-how-the-server-endpoints-work-remove-specifically",
      title:
        "filepond - confused how the server endpoints work - &#39;remove&#39; specifically",
    },
    {
      tags: ["javascript", "jquery", "anchor", "fragment-identifier"],
      owner: {
        account_id: 11297,
        reputation: 131533,
        user_id: 21709,
        user_type: "registered",
        accept_rate: 100,
        profile_image:
          "https://www.gravatar.com/avatar/3ea9c684a2db319df788cecc6c98f9cd?s=256&d=identicon&r=PG",
        display_name: "Philip Morton",
        link: "https://stackoverflow.com/users/21709/philip-morton",
      },
      is_answered: true,
      view_count: 812809,
      accepted_answer_id: 298513,
      answer_count: 21,
      score: 929,
      last_activity_date: 1727447936,
      creation_date: 1227008102,
      last_edit_date: 1655940760,
      question_id: 298503,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/298503/how-can-you-check-for-a-hash-in-a-url-using-javascript",
      title: "How can you check for a #hash in a URL using JavaScript?",
    },
    {
      tags: ["javascript", "jquery", "jquery-ui-datepicker"],
      owner: {
        account_id: 3705300,
        reputation: 2666,
        user_id: 3084005,
        user_type: "registered",
        accept_rate: 72,
        profile_image: "https://i.sstatic.net/5v4xZ.jpg?s=256",
        display_name: "Attila Naghi",
        link: "https://stackoverflow.com/users/3084005/attila-naghi",
      },
      is_answered: false,
      view_count: 8469,
      answer_count: 1,
      score: 2,
      last_activity_date: 1727445825,
      creation_date: 1533739566,
      last_edit_date: 1533740693,
      question_id: 51749586,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/51749586/how-to-translate-jquery-ui-datepicker-in-multiple-language",
      title: "How to translate jquery ui datepicker in multiple language?",
    },
    {
      tags: ["javascript", "jquery", "iphone", "ipad", "asp.net-mvc-5"],
      owner: {
        account_id: 3499157,
        reputation: 10664,
        user_id: 2926340,
        user_type: "registered",
        accept_rate: 52,
        profile_image:
          "https://www.gravatar.com/avatar/0b6a9d7f9d1f87373a15514d7ce671cc?s=256&d=identicon&r=PG&f=y&so-version=2",
        display_name: "Sergino",
        link: "https://stackoverflow.com/users/2926340/sergino",
      },
      is_answered: false,
      view_count: 10034,
      answer_count: 1,
      score: 6,
      last_activity_date: 1727445825,
      creation_date: 1388044504,
      last_edit_date: 1388046389,
      question_id: 20781247,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/20781247/form-submit-not-working-on-ipad-and-iphone",
      title: "$(&quot;form&quot;).submit not working on ipad and iphone",
    },
    {
      tags: [
        "javascript",
        "jquery",
        "woocommerce",
        "jquery-select2",
        "jquery-select2-4",
      ],
      owner: {
        account_id: 216954,
        reputation: 20109,
        user_id: 472501,
        user_type: "registered",
        accept_rate: 86,
        profile_image:
          "https://www.gravatar.com/avatar/010bd6b16b0f7955f8c3bdb9a4c8d88c?s=256&d=identicon&r=PG",
        display_name: "Brett",
        link: "https://stackoverflow.com/users/472501/brett",
      },
      is_answered: false,
      view_count: 1841,
      answer_count: 2,
      score: 41,
      last_activity_date: 1727445153,
      creation_date: 1559255103,
      last_edit_date: 1640123214,
      question_id: 56386378,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/56386378/having-trouble-working-with-selectwoo-instances-of-select2-within-woocommerce",
      title:
        "Having trouble working with SelectWoo instances of Select2 within WooCommerce",
    },
    {
      tags: ["python", "jquery", "jupyter-notebook", "ipywidgets"],
      owner: {
        account_id: 3295418,
        reputation: 389,
        user_id: 2772805,
        user_type: "registered",
        profile_image: "https://i.sstatic.net/7N6Ln.jpg?s=256",
        display_name: "PBrockmann",
        link: "https://stackoverflow.com/users/2772805/pbrockmann",
      },
      is_answered: false,
      view_count: 40,
      answer_count: 1,
      score: 2,
      last_activity_date: 1727443413,
      creation_date: 1727201372,
      last_edit_date: 1727443413,
      question_id: 79019852,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/79019852/jquery-in-display-function-of-a-python-notebook",
      title: "jQuery in display function of a Python notebook",
    },
    {
      tags: ["javascript", "jquery", "asp.net-mvc", "reportviewerformvc"],
      owner: {
        account_id: 943075,
        reputation: 971,
        user_id: 970826,
        user_type: "registered",
        accept_rate: 19,
        profile_image:
          "https://www.gravatar.com/avatar/65c9d0eac6e46e68100ec8bbc2b776a6?s=256&d=identicon&r=PG&f=y&so-version=2",
        display_name: "AMDI",
        link: "https://stackoverflow.com/users/970826/amdi",
      },
      is_answered: false,
      view_count: 36,
      answer_count: 0,
      score: -1,
      last_activity_date: 1727443061,
      creation_date: 1727407547,
      last_edit_date: 1727443061,
      question_id: 79029740,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/79029740/get-id-of-viewreport-button-on-report-viewer",
      title: "get id of &#39;ViewReport&#39; button on report viewer",
    },
    {
      tags: ["php", "jquery", "mysql", "dynamic", "elixir-jason"],
      owner: {
        account_id: 5018445,
        reputation: 1,
        user_id: 4032627,
        user_type: "registered",
        profile_image:
          "https://graph.facebook.com/100002149186665/picture?type=large",
        display_name: "Salim Al-Adawi",
        link: "https://stackoverflow.com/users/4032627/salim-al-adawi",
      },
      is_answered: false,
      view_count: 47,
      closed_date: 1727434587,
      answer_count: 0,
      score: -2,
      last_activity_date: 1727435870,
      creation_date: 1727433539,
      last_edit_date: 1727435870,
      question_id: 79030962,
      link: "https://stackoverflow.com/questions/79030962/dynamic-html-tables-mysql-php",
      closed_reason: "Needs details or clarity",
      title: "Dynamic HTML Tables, MySQL ,PHP",
    },
    {
      tags: ["java", "jquery", "http", "servlets"],
      owner: {
        account_id: 457201,
        reputation: 98,
        user_id: 856378,
        user_type: "registered",
        profile_image:
          "https://www.gravatar.com/avatar/6941434e30e675e5397ef0d7af865787?s=256&d=identicon&r=PG",
        display_name: "yokuyuki",
        link: "https://stackoverflow.com/users/856378/yokuyuki",
      },
      is_answered: false,
      view_count: 10296,
      answer_count: 1,
      score: 2,
      last_activity_date: 1727434860,
      creation_date: 1344530158,
      question_id: 11887974,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/11887974/how-to-accept-both-multipart-and-application-x-www-form-urlencoded",
      title:
        "How to accept both multipart and application/x-www-form-urlencoded?",
    },
    {
      tags: ["jquery", "ajax", "vb.net", "post", "httpwebrequest"],
      owner: {
        account_id: 103637,
        reputation: 10460,
        user_id: 277480,
        user_type: "registered",
        accept_rate: 68,
        profile_image: "https://i.sstatic.net/JMaKB.jpg?s=256",
        display_name: "StealthRT",
        link: "https://stackoverflow.com/users/277480/stealthrt",
      },
      is_answered: false,
      view_count: 9001,
      answer_count: 1,
      score: 1,
      last_activity_date: 1727431350,
      creation_date: 1394823437,
      last_edit_date: 1394847563,
      question_id: 22413507,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/22413507/vb-net-post-via-httpwebrequest",
      title: "VB.net POST via HttpWebRequest",
    },
    {
      tags: ["javascript", "jquery", "css", "centering", "slick.js"],
      owner: {
        account_id: 7739166,
        reputation: 789,
        user_id: 5859663,
        user_type: "registered",
        accept_rate: 81,
        profile_image: "https://i.sstatic.net/nQ0bH.png?s=256",
        display_name: "DiscreteTomatoes",
        link: "https://stackoverflow.com/users/5859663/discretetomatoes",
      },
      is_answered: true,
      view_count: 3007,
      accepted_answer_id: 43924145,
      answer_count: 2,
      score: 0,
      last_activity_date: 1727428426,
      creation_date: 1494529692,
      last_edit_date: 1494542560,
      question_id: 43923764,
      content_license: "CC BY-SA 3.0",
      link: "https://stackoverflow.com/questions/43923764/slickjs-carousel-centermode-not-working",
      title: "SlickJS carousel centerMode not working",
    },
    {
      tags: ["javascript", "jquery", "spotfire", "spotfire-analyst"],
      owner: {
        account_id: 29751913,
        reputation: 1,
        user_id: 22801628,
        user_type: "registered",
        profile_image:
          "https://lh3.googleusercontent.com/a/ACg8ocLi1vdUKBezpn8K0MAZ05kCseohcyVcHXZ43WkyBop4=k-s256",
        display_name: "Arihant Jain",
        link: "https://stackoverflow.com/users/22801628/arihant-jain",
      },
      is_answered: false,
      view_count: 192,
      answer_count: 0,
      score: 0,
      last_activity_date: 1727420911,
      creation_date: 1698244110,
      question_id: 77360404,
      content_license: "CC BY-SA 4.0",
      link: "https://stackoverflow.com/questions/77360404/tibco-spotfire-datepicker-function-error-in-12-5-0",
      title: "TIBCO Spotfire datepicker function error in 12.5.0",
    },
  ],
  has_more: true,
  quota_max: 300,
  quota_remaining: 261,
};

export const dummyResTags = {
  items: [
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2535178,
      name: "javascript",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 2211377,
      name: "python",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1920661,
      name: "java",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1622884,
      name: "c#",
    },
    {
      collectives: [
        {
          tags: ["php"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective where developers working with PHP can learn and connect about the open source scripting language.",
          link: "/collectives/php",
          name: "PHP",
          slug: "php",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1468304,
      name: "php",
    },
    {
      collectives: [
        {
          tags: ["android", "ios"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
          link: "/collectives/mobile-dev",
          name: "Mobile Development",
          slug: "mobile-dev",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1420347,
      name: "android",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1190127,
      name: "html",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 1034237,
      name: "jquery",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 812063,
      name: "c++",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 807414,
      name: "css",
    },
    {
      collectives: [
        {
          tags: ["android", "ios"],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective for developers who want to share their knowledge and learn more about mobile development practices and platforms",
          link: "/collectives/mobile-dev",
          name: "Mobile Development",
          slug: "mobile-dev",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 688678,
      name: "ios",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 674151,
      name: "sql",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 662100,
      name: "mysql",
    },
    {
      collectives: [
        {
          tags: [
            "r-caret",
            "stringr",
            "tidyr",
            "data.table",
            "tidyverse",
            "zoo",
            "purrr",
            "r",
            "lubridate",
            "knitr",
            "shinyapps",
            "r-package",
            "shiny-server",
            "rvest",
            "rstudio",
            "r-raster",
            "shiny",
            "quantmod",
            "rlang",
            "forcats",
            "shinydashboard",
            "ggplot2",
            "dplyr",
            "readr",
            "tibble",
            "dtplyr",
            "plyr",
          ],
          external_links: [
            {
              type: "support",
              link: "https://stackoverflow.com/contact?topic=15",
            },
          ],
          description:
            "A collective where data scientists and AI researchers gather to find, share, and learn about R and other subtags like knitr and dplyr.",
          link: "/collectives/r-language",
          name: "R Language",
          slug: "r-language",
        },
      ],
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 509614,
      name: "r",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 481120,
      name: "reactjs",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 474199,
      name: "node.js",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 417832,
      name: "arrays",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 406633,
      name: "c",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 374828,
      name: "asp.net",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 361413,
      name: "json",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 343555,
      name: "python-3.x",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 340416,
      name: ".net",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 338359,
      name: "ruby-on-rails",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 336211,
      name: "sql-server",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 335592,
      name: "swift",
    },
    {
      has_synonyms: false,
      is_moderator_only: false,
      is_required: false,
      count: 313095,
      name: "django",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 306736,
      name: "angular",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 292212,
      name: "objective-c",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 289339,
      name: "excel",
    },
    {
      has_synonyms: true,
      is_moderator_only: false,
      is_required: false,
      count: 288793,
      name: "pandas",
    },
  ],
  has_more: true,
  quota_max: 300,
  quota_remaining: 299,
};
